import type { Metadata } from "next";
import Navbar from "@/components/navbar";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { ActiveProvider } from "@/context/ActiveContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          async
          src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r121/three.min.js"
        ></script>
      </head>
      <body className={`${inter.className}  bg-white dark:bg-[#212121]`}>
        <Providers>
          <ActiveProvider>
            <Navbar />
            {children}
          </ActiveProvider>
        </Providers>
      </body>
    </html>
  );
}
